package cr.talent.model;

/**
 * Class that represents a contact email to contact the administrators of the Talent system, generated by
 * an authenticated user.
 *
 * @author Fabián Roberto Leandro
 */
public class AuthenticatedContactEmail extends ContactEmail {

    /**
     * The user that submitted the Contact Us request.
     */
    private TechnicalResource technicalResource;

    public AuthenticatedContactEmail(){}

    public User getTechnicalResource() {
        return technicalResource;
    }

    public void setTechnicalResource(TechnicalResource user) {
        this.technicalResource = user;
    }
}
