package cr.talent.model;

/**
 * Class that represents a contact email to contact the administrators of the Talent system, generated by
 * an authenticated user.
 *
 * @author Fabián Roberto Leandro
 */
public class AuthenticatedContactEmail extends ContactEmail {

    /**
     * The user that submitted the Contact Us request.
     */
    private User user;

    public AuthenticatedContactEmail(){ }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }
}
